# This file is machine-generated - editing it directly is not advised

[[InnerExamples]]
path = "/home/fraser/.julia/dev/InnerExamples"
uuid = "d62495ee-cbdc-46e5-b0f0-aa0d75334c7b"
version = "0.1.0"
